# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('AU', 'Automotive'), ('CL', 'Clothing'), ('SO', 'Software')], default='AU', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, help_text='Separate tags with commas. Ex: python,django,flask', max_length=100, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=75)),
                ('answer', models.CharField(max_length=75)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bots.Bot')),
            ],
        ),
    ]
