# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20171127_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='bot',
        ),
        migrations.DeleteModel(
            name='Knowledge',
        ),
    ]
