# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_auto_20171127_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='category',
            field=models.IntegerField(choices=[(1, 'Automotive'), (2, 'Clothing'), (3, 'Software')], default=1),
        ),
    ]
