# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_auto_20171127_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
