# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_bot_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.Bot'),
        ),
    ]
