# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_bot_is_archived'),
        ('bots', '0006_auto_20171128_0335'),
    ]

    operations = [
    ]
