# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_merge_20171205_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
